# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formCriarConta.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_Email = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Email.setGeometry(QtCore.QRect(440, 250, 321, 30))
        self.lineEdit_Email.setObjectName("lineEdit_Email")
        self.pushButton_Criar_Conta = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Criar_Conta.setGeometry(QtCore.QRect(440, 520, 320, 40))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(12)
        self.pushButton_Criar_Conta.setFont(font)
        self.pushButton_Criar_Conta.setObjectName("pushButton_Criar_Conta")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(440, 120, 191, 30))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(430, 50, 341, 61))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(22)
        self.label_3.setFont(font)
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 380, 370))
        self.label_2.setText("")
        img_path = os.path.join(os.path.dirname(__file__), "Imagens", "Logo.jpg")
        self.label_2.setPixmap(QtGui.QPixmap(img_path))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.lineEdit_Nome_Utilizador = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Nome_Utilizador.setGeometry(QtCore.QRect(440, 160, 321, 30))
        self.lineEdit_Nome_Utilizador.setObjectName("lineEdit_Nome_Utilizador")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(440, 210, 191, 30))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(440, 300, 191, 30))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit_Palavra_Passe = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Palavra_Passe.setGeometry(QtCore.QRect(440, 340, 321, 30))
        self.lineEdit_Palavra_Passe.setObjectName("lineEdit_Palavra_Passe")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(440, 380, 231, 30))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEdit_Confirmar_Palavra_Passe = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Confirmar_Palavra_Passe.setGeometry(QtCore.QRect(440, 420, 321, 30))
        self.lineEdit_Confirmar_Palavra_Passe.setObjectName("lineEdit_Confirmar_Palavra_Passe")
        self.pushButton_Toggle_Palavra_Passe = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Toggle_Palavra_Passe.setGeometry(QtCore.QRect(440, 470, 321, 30))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(10)
        self.pushButton_Toggle_Palavra_Passe.setFont(font)
        self.pushButton_Toggle_Palavra_Passe.setObjectName("pushButton_Toggle_Palavra_Passe")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Criação de Conta"))
        self.pushButton_Criar_Conta.setText(_translate("MainWindow", "Criar conta"))
        self.label.setText(_translate("MainWindow", "Nome de Utilizador:"))
        self.label_3.setText(_translate("MainWindow", "Diz-nos quem tu és!"))
        self.label_5.setText(_translate("MainWindow", "Email:"))
        self.label_6.setText(_translate("MainWindow", "Palavra Passe:"))
        self.label_7.setText(_translate("MainWindow", "Confirmar Palavra Passe:"))
        self.pushButton_Toggle_Palavra_Passe.setText(_translate("MainWindow", "Mostrar/Ocultar passwords"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
