# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\formCriarAlterarCategoria.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_Voltar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Voltar.setGeometry(QtCore.QRect(230, 490, 230, 40))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(10)
        self.pushButton_Voltar.setFont(font)
        self.pushButton_Voltar.setObjectName("pushButton_Voltar")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(140, 30, 531, 50))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(26)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 250, 120, 41))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit_Id = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Id.setGeometry(QtCore.QRect(230, 250, 480, 40))
        self.lineEdit_Id.setObjectName("lineEdit_Id")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(80, 490, 120, 40))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(16)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.pushButton_CriarAlterar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_CriarAlterar.setGeometry(QtCore.QRect(480, 490, 230, 40))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(10)
        self.pushButton_CriarAlterar.setFont(font)
        self.pushButton_CriarAlterar.setObjectName("pushButton_CriarAlterar")
        self.lineEdit_Id_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Id_2.setGeometry(QtCore.QRect(230, 310, 480, 40))
        self.lineEdit_Id_2.setObjectName("lineEdit_Id_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 310, 140, 41))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Criar ou Alterar Fornecedor"))
        self.pushButton_Voltar.setText(_translate("MainWindow", "Voltar"))
        self.label_5.setText(_translate("MainWindow", "Criar / Alterar Categoria"))
        self.label.setText(_translate("MainWindow", "Id:"))
        self.checkBox.setText(_translate("MainWindow", "Ativo"))
        self.pushButton_CriarAlterar.setText(_translate("MainWindow", "Criar / Alterar"))
        self.label_2.setText(_translate("MainWindow", "Designação:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
