# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interfaces/formCriarAlterarEncomendaArmazem.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 750)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo.setGeometry(QtCore.QRect(250, 10, 600, 40))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(22)
        self.label_titulo.setFont(font)
        #self.label_titulo.setAlignment(QtCore.Qt.Qt::AlignmentFlag::AlignCenter)
        self.label_titulo.setObjectName("label_titulo")
        self.groupBox_Catalogo = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Catalogo.setGeometry(QtCore.QRect(20, 80, 520, 550))
        self.groupBox_Catalogo.setObjectName("groupBox_Catalogo")
        self.lineEdit_Pesquisar = QtWidgets.QLineEdit(self.groupBox_Catalogo)
        self.lineEdit_Pesquisar.setGeometry(QtCore.QRect(10, 30, 220, 35))
        self.lineEdit_Pesquisar.setObjectName("lineEdit_Pesquisar")
        self.pushButton_Pesquisar = QtWidgets.QPushButton(self.groupBox_Catalogo)
        self.pushButton_Pesquisar.setGeometry(QtCore.QRect(350, 30, 80, 35))
        self.pushButton_Pesquisar.setObjectName("pushButton_Pesquisar")
        self.comboBox_CategoriaFiltro = QtWidgets.QComboBox(self.groupBox_Catalogo)
        self.comboBox_CategoriaFiltro.setGeometry(QtCore.QRect(240, 30, 100, 35))
        self.comboBox_CategoriaFiltro.setObjectName("comboBox_CategoriaFiltro")
        self.pushButton_Filtrar = QtWidgets.QPushButton(self.groupBox_Catalogo)
        self.pushButton_Filtrar.setGeometry(QtCore.QRect(440, 30, 70, 35))
        self.pushButton_Filtrar.setObjectName("pushButton_Filtrar")
        self.tableView_Produtos = QtWidgets.QTableView(self.groupBox_Catalogo)
        self.tableView_Produtos.setGeometry(QtCore.QRect(10, 80, 500, 370))
        self.tableView_Produtos.setObjectName("tableView_Produtos")
        self.label_q = QtWidgets.QLabel(self.groupBox_Catalogo)
        self.label_q.setGeometry(QtCore.QRect(10, 470, 91, 30))
        self.label_q.setObjectName("label_q")
        self.lineEdit_Quantidade = QtWidgets.QLineEdit(self.groupBox_Catalogo)
        self.lineEdit_Quantidade.setGeometry(QtCore.QRect(100, 470, 60, 35))
        self.lineEdit_Quantidade.setObjectName("lineEdit_Quantidade")
        self.pushButton_Adicionar = QtWidgets.QPushButton(self.groupBox_Catalogo)
        self.pushButton_Adicionar.setGeometry(QtCore.QRect(300, 470, 210, 35))
        self.pushButton_Adicionar.setObjectName("pushButton_Adicionar")
        self.groupBox_Carrinho = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Carrinho.setGeometry(QtCore.QRect(560, 80, 520, 550))
        self.groupBox_Carrinho.setObjectName("groupBox_Carrinho")
        self.tableView_Carrinho = QtWidgets.QTableView(self.groupBox_Carrinho)
        self.tableView_Carrinho.setGeometry(QtCore.QRect(10, 30, 500, 420))
        self.tableView_Carrinho.setObjectName("tableView_Carrinho")
        self.pushButton_Remover = QtWidgets.QPushButton(self.groupBox_Carrinho)
        self.pushButton_Remover.setGeometry(QtCore.QRect(10, 470, 500, 35))
        self.pushButton_Remover.setObjectName("pushButton_Remover")
        self.pushButton_Voltar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Voltar.setGeometry(QtCore.QRect(20, 660, 150, 45))
        self.pushButton_Voltar.setObjectName("pushButton_Voltar")
        self.pushButton_Concluir = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Concluir.setGeometry(QtCore.QRect(850, 660, 230, 45))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(11)
        self.pushButton_Concluir.setFont(font)
        self.pushButton_Concluir.setObjectName("pushButton_Concluir")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Encomenda Armazém - Gestão de Itens"))
        self.label_titulo.setText(_translate("MainWindow", "Registar Encomenda Armazém"))
        self.groupBox_Catalogo.setTitle(_translate("MainWindow", "1. Selecionar Produtos (Catálogo)"))
        self.lineEdit_Pesquisar.setPlaceholderText(_translate("MainWindow", "Pesquisar nome..."))
        self.pushButton_Pesquisar.setText(_translate("MainWindow", "Buscar"))
        self.pushButton_Filtrar.setText(_translate("MainWindow", "Filtrar"))
        self.label_q.setText(_translate("MainWindow", "Quantidade:"))
        self.pushButton_Adicionar.setText(_translate("MainWindow", "Adicionar à Encomenda"))
        self.groupBox_Carrinho.setTitle(_translate("MainWindow", "2. Itens da Encomenda (Carrinho)"))
        self.pushButton_Remover.setText(_translate("MainWindow", "Remover Artigo Selecionado"))
        self.pushButton_Voltar.setText(_translate("MainWindow", "Voltar"))
        self.pushButton_Concluir.setText(_translate("MainWindow", "Concluir a encomenda"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
